services:
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    container_name: mysql_java
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demodb
      MYSQL_USER: userteste
      MYSQL_PASSWORD: root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"